#!/bin/sh
#  Hook to prevent commits on the 'main' branch

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You cannot commit directly to the main branch!"
  echo "Please create a feature branch or use pull requests."
  exit 1
fi